#!/usr/bin/env sh

revision='89c5c976195342344f4caffce016c2de7abb8802'

if [ -f "$(dirname $0)/../staging/u-boot-${revision}/tools/mkimage" ]; then
    echo ":: 'mkimage' file exists, copying it to build directory"
    mkdir -p "$(dirname $0)/../build"
    cp -v "$(dirname $0)/../staging/u-boot-${revision}/tools/mkimage" "$(dirname $0)/../build"
    echo ":: if you want to rebuild it from scratch,"
    echo "::    remove $(dirname $0)/../staging/u-boot-${revision}"

    exit 0
fi

set -o errexit
set -o xtrace

mkdir -p "$(dirname $0)/../build" "$(dirname $0)/../staging"

wget -O- 'https://gitlab.denx.de/u-boot/u-boot/-/archive/'${revision}'/u-boot-'${revision}'.tar.gz' | tar zxf - -C "$(dirname $0)/../staging"
make -C "$(dirname $0)/../staging/u-boot-${revision}" mx28evk_defconfig CC=$(which gcc)
make -C "$(dirname $0)/../staging/u-boot-${revision}" tools-only CC=$(which gcc)
cp -v "$(dirname $0)/../staging/u-boot-${revision}/tools/mkimage" "$(dirname $0)/../build"
