#!/usr/bin/env python3

import os
import sys
import subprocess


if 'CC' not in os.environ:
    try:
        os.environ['CC'] = os.environ['CROSS_COMPILE'] + 'gcc'
    except KeyError:
        print('Set "CC" or "CROSS_COMPILE" environment', file=sys.stderr)
        print('E.g.: export CROSS_COMPILE=/opt/gcc-linaro-arm-eabi/bin/arm-eabi-', file=sys.stderr)
        sys.exit(13)

if not os.path.exists(os.environ['CC']):
    print('CC={0} does not exist'.format(os.environ['CC']), file=sys.stderr)
    sys.exit(13)

print('## CC .................... {0}'.format(os.environ['CC']))

build_dir = os.path.join(os.path.dirname(os.path.realpath(sys.argv[0])), '..', 'build')
build_file = os.path.join(os.path.dirname(os.path.realpath(sys.argv[0])), '..', 'boz')

os.makedirs(build_dir, exist_ok=True)

subprocess.call(['cmake', '-E', 'chdir', build_dir, 'cmake', os.getcwd()])
subprocess.call(['cmake', '--build', build_dir, '--clean-first'])

with open(build_file, 'w') as fil:
    print('cmake --build {0} "$@"'.format(build_dir), file=fil)

os.chmod(build_file, 0o755)
