#!/usr/bin/env sh

revision='2793a657ab7a22487d21c1b020957806f8ae8383'

if [ -f "$(dirname $0)/../staging/mxsldr-${revision}/mxsldr" ]; then
    echo ":: 'mxsldr' file exists, copying it to build directory"
    mkdir -p "$(dirname $0)/../build"
    cp -v "$(dirname $0)/../staging/mxsldr-${revision}/mxsldr" "$(dirname $0)/../build"
    echo ":: if you want to rebuild it from scratch,"
    echo "::    remove $(dirname $0)/../staging/mxsldr-${revision}"

    exit 0
fi

set -o errexit
set -o xtrace

mkdir -p "$(dirname $0)/build" "$(dirname $0)/../staging"

wget -O- 'https://gitlab.denx.de/denx/mxsldr/-/archive/'${revision}'/u-boot-'${revision}'.tar.gz' | tar zxf - -C "$(dirname $0)/../staging"
make -C "$(dirname $0)/../staging/mxsldr-${revision}" CC=$(which gcc)
cp -v "$(dirname $0)/../staging/mxsldr-${revision}/mxsldr" "$(dirname $0)/../build"
